import type { NextConfig } from "next";

// Fully static export: no serverless functions and no image optimizer. Images are
// pre-resized by scripts/photos/ingest.ts and served from img.jpvalery.photo (R2).
// Redirects and headers live in vercel.json (generated by scripts/gen/vercel-json.ts).
const config: NextConfig = {
	output: "export",
	images: { unoptimized: true },
	trailingSlash: false,
	typedRoutes: true,
	reactStrictMode: true,
};

export default config;
