import type { CSSProperties } from "react";
import type { PhotoView } from "../../lib/photos.ts";
import { SIZES, type SizesPreset } from "./sizes.ts";
import { jpegUrl, srcSet } from "./url.ts";

type Props = {
	photo: PhotoView;
	sizes: SizesPreset;
	/** The page's largest above-the-fold image: loads eagerly at high priority. */
	priority?: boolean;
	placeholder?: "color" | "blur" | "none";
	/** Decorative copies (back prints in a pile) are hidden from assistive tech. */
	decorative?: boolean;
	/** Skip variants wider than this when the slot can never be that large. */
	maxWidth?: number;
	className?: string;
	style?: CSSProperties;
};

/**
 * Every photo on the site goes through here. Variants are pre-generated by
 * scripts/photos/ingest.ts, so the browser fetches a sized AVIF/WebP straight from
 * the CDN and nothing is resized at request time.
 */
export function Photo({
	photo,
	sizes,
	priority,
	placeholder = "color",
	decorative,
	maxWidth,
	className,
	style,
}: Props) {
	const fit = maxWidth ? photo.widths.filter((w) => w <= maxWidth) : photo.widths;
	const widths = fit.length ? fit : photo.widths.slice(0, 1);
	const background: CSSProperties =
		placeholder === "blur"
			? { backgroundImage: `url(${photo.lqip})`, backgroundSize: "cover", backgroundColor: photo.color }
			: placeholder === "color"
				? { backgroundColor: photo.color }
				: {};
	return (
		<picture style={{ display: "contents" }}>
			<source type="image/avif" srcSet={srcSet(photo.hash, widths, "avif")} sizes={SIZES[sizes]} />
			<source type="image/webp" srcSet={srcSet(photo.hash, widths, "webp")} sizes={SIZES[sizes]} />
			<img
				src={jpegUrl(photo.hash)}
				width={photo.width}
				height={photo.height}
				alt={decorative ? "" : photo.alt}
				aria-hidden={decorative || undefined}
				loading={priority ? "eager" : "lazy"}
				fetchPriority={priority ? "high" : undefined}
				decoding="async"
				className={className}
				style={{ ...background, ...style }}
			/>
		</picture>
	);
}
